name: Run Performance Test
on:
  push:
    branches:
      - master
      - BAH-2105-CI
    paths-ignore:
      - "**.md"
  workflow_dispatch:
    inputs:
      TRAFFIC_LOAD:
        description: 'Traffic Load Simulation Type'
        required: true
        type: choice
        default: standard
        options:
          - standard
          - high
          - peak
env:
  LOAD_SIMULATION_TYPE: ${{ github.event.inputs.TRAFFIC_LOAD || 'standard' }}
jobs:
  performance-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ./gradlew build
      - name: Run Performance Test
        run: ./gradlew gatlingRun
      - name: Checkout reports branch
        uses: actions/checkout@v2
        with:
          repository: Bahmni/performance-test
          ref: gh-pages
          path: reports
          persist-credentials: false
      - name: Copy reports
        run: |
          ls -lrt
          cp -r build/reports/gatling/bahmni* reports
          mv reports/bahmni* reports/${{github.run_number}}
      - name: Publish report
        working-directory: reports/
        run: |
          git config user.name ${{ secrets.BAHMNI_USERNAME}}
          git config user.email ${{ secrets.BAHMNI_EMAIL}}
          git add .
          git commit -m "Publishing report /${{github.run_number}}"
          git push 'https://${{ secrets.BAHMNI_USERNAME}}:${{ secrets.BAHMNI_PAT}}@github.com/bahmni/performance-test.git' gh-pages
