name: Run Performance Test
on:
  push:
    branches:
      - master
      - BAH-2105-CI
    paths-ignore:
      - "**.md"

jobs:
  build-upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ./gradlew build
